### ISSUE TITLE
Getting list of cities is too slow to load.

### ISSUE THREAD

**Issue by lokeshkrajput** [swapnilnakhate10/Cities-States-Country#2]
Getting list of cities is too slow to load.

Below code is too slow to execute: 
**worldMapData.getAllCitiesFromState(<any_state>);**

Adding a country parameter to it may be more efficient i.e.
**worldMapData.getAllCitiesFromState(<any_country>, <any_state>);**

**Comment by swapnilnakhate10** [comment]
Fixed performance issue in 2.1.0 version.
